[package]
name = "robot_os_shell"
version = "0.1.0"
edition = "2021"

[features]
rvv     = ["robot_os_arch/rvv", "robot_os_ml/rvv", "robot_os_camera/rvv"]
no-ml   = ["robot_os_behavior/no-ml"]
no-mmu  = []
esp32c3 = ["no-mmu", "no-ml"]

[dependencies]
robot_os_fs = { workspace = true }
robot_os_net = { workspace = true }
robot_os_sched = { workspace = true }
robot_os_mm = { workspace = true }
robot_os_drivers = { workspace = true }
robot_os_robot = { workspace = true }
robot_os_arch = { workspace = true }
robot_os_ml     = { workspace = true }
robot_os_camera = { workspace = true }
robot_os_common = { workspace = true }
robot_os_config = { workspace = true }
robot_os_imu    = { workspace = true }
robot_os_baro     = { workspace = true }
robot_os_behavior = { workspace = true }
robot_os_ahrs     = { workspace = true }
robot_os_gps       = { workspace = true }
robot_os_flight    = { workspace = true }
robot_os_telemetry = { workspace = true }
robot_os_nav       = { workspace = true }
