//! `robot_os_limits` — generated compile-time constants from `.config`
//!
//! RFC-0026 Phase C2.  Every numeric, bool, and string option from the
//! Kconfig `.config` file is available here as a `pub const`.
//!
//! This crate is auto-generated by `build.rs` which reads the workspace
//! `.config` file via `phanes_config::parse_config` + `emit_rust`.
//!
//! **DO NOT hand-edit the generated constants.**  Run `make menuconfig`
//! or `make defconfig-<profile>` and rebuild to change values.
//!
//! # Usage
//!
//! ```rust,ignore
//! use robot_os_limits::MAX_TASKS;
//! let table: [u8; MAX_TASKS] = [0; MAX_TASKS];
//! ```
//!
//! Status 2026-08-20: the Phase C3 migration has happened. These
//! constants are consumed across `crates/sched/src/task.rs`,
//! `crates/net/src/{socket,tcp}.rs`, `crates/mm/src/pmm.rs`,
//! `crates/ipc/`, `crates/fs/src/vfs.rs`, `crates/ota/src/lib.rs` and
//! `kernel/src/main.rs` itself. The earlier note here saying the crate
//! was "generated but not yet wired into the kernel" was stale and has
//! been removed — it was the kind of comment that makes a reader
//! re-do work that already exists.

#![no_std]
#![allow(unused)]

// Include the file generated by build.rs into OUT_DIR.
// build.rs writes `generated.rs` during `cargo build -p robot_os_limits`.
include!(concat!(env!("OUT_DIR"), "/generated.rs"));
