[package]
name = "robot_os_telemetry"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
robot_os_channel = { workspace = true }
robot_os_ahrs    = { workspace = true }
robot_os_gps     = { workspace = true }
robot_os_imu     = { workspace = true }
robot_os_drivers = { workspace = true }
robot_os_net     = { workspace = true }
