#!/usr/bin/env python3
"""F18 — Generate an Ed25519 key pair for development use.

Writes:
  tools/keys/dev_priv.bin   (32 bytes raw seed — KEEP SECRET)
  tools/keys/dev_pub.bin    (32 bytes raw public key)
  tools/keys/dev_pub.rs     (Rust byte array to embed in kernel)

Requires the `cryptography` Python package. Install with:
    pip install cryptography
"""

import os
import sys
from pathlib import Path

try:
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    from cryptography.hazmat.primitives import serialization
except ImportError:
    print("error: install the 'cryptography' package: pip install cryptography", file=sys.stderr)
    sys.exit(1)

KEY_DIR = Path(__file__).parent / "keys"
PRIV_PATH = KEY_DIR / "dev_priv.bin"
PUB_PATH = KEY_DIR / "dev_pub.bin"
PUB_RS_PATH = KEY_DIR / "dev_pub.rs"

KEY_DIR.mkdir(exist_ok=True, parents=True)

if PRIV_PATH.exists():
    print(f"warning: {PRIV_PATH} already exists. delete it first if you want to regenerate.")
    sys.exit(0)

priv = Ed25519PrivateKey.generate()
priv_raw = priv.private_bytes(
    encoding=serialization.Encoding.Raw,
    format=serialization.PrivateFormat.Raw,
    encryption_algorithm=serialization.NoEncryption(),
)
pub = priv.public_key()
pub_raw = pub.public_bytes(
    encoding=serialization.Encoding.Raw,
    format=serialization.PublicFormat.Raw,
)

PRIV_PATH.write_bytes(priv_raw)
os.chmod(PRIV_PATH, 0o600)
PUB_PATH.write_bytes(pub_raw)

pub_bytes = ", ".join(f"0x{b:02x}" for b in pub_raw)
PUB_RS_PATH.write_text(
    "// Auto-generated by tools/gen_dev_key.py — DEV ONLY\n"
    "// Paste into crates/ota/src/secure_boot.rs SECURE_BOOT_PUBKEY\n"
    f"pub static SECURE_BOOT_PUBKEY: [u8; 32] = [{pub_bytes}];\n"
)

print(f"✓ private: {PRIV_PATH} (mode 0600)")
print(f"✓ public : {PUB_PATH}")
print(f"✓ rust   : {PUB_RS_PATH}")
print("\nTo use: copy the contents of dev_pub.rs into crates/ota/src/secure_boot.rs")
