//! OT05 — embed the production Ed25519 public key at compile time.
//!
//! Reads `tools/keys/prod_pub.bin` (32 bytes raw Ed25519 public key) and
//! emits a Rust array literal to `$OUT_DIR/secure_boot_pubkey.rs`. The crate
//! `include!()`s that file from `secure_boot.rs`. If the file is missing
//! (typical for dev builds and CI), the array is all zeros — the kernel
//! treats that as "no trusted key" → BootTrust::Unverified.
//!
//! Override path with PROD_PUBKEY_PATH env var if you need a different key
//! per build (e.g. staging vs production fleets).
//!
//! WHY this is here, not a feature flag:
//! - A feature flag would force every developer to pass `--features prod-key`,
//!   easy to forget. Reading a file is automatic and explicit.
//! - The build artifact captures which key is embedded — the kernel binary
//!   can be reproduced byte-for-byte from the same prod_pub.bin.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

const PUBKEY_LEN: usize = 32;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let dest = out_dir.join("secure_boot_pubkey.rs");

    // Default: tools/keys/prod_pub.bin relative to this crate.
    // ota crate is at crates/ota/, so up two levels = repo root.
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR not set");
    let default_path = PathBuf::from(&manifest_dir)
        .join("..").join("..")
        .join("tools").join("keys").join("prod_pub.bin");
    let key_path = env::var("PROD_PUBKEY_PATH")
        .map(PathBuf::from)
        .unwrap_or(default_path);

    println!("cargo:rerun-if-changed={}", key_path.display());
    println!("cargo:rerun-if-env-changed=PROD_PUBKEY_PATH");

    let bytes: [u8; PUBKEY_LEN] = match fs::read(&key_path) {
        Ok(data) if data.len() == PUBKEY_LEN => {
            let mut arr = [0u8; PUBKEY_LEN];
            arr.copy_from_slice(&data);
            println!("cargo:warning=secure_boot: embedding prod pubkey from {}",
                key_path.display());
            arr
        }
        Ok(data) => {
            println!("cargo:warning=secure_boot: {} has wrong size ({} != {}), \
                using all-zero dev key", key_path.display(), data.len(), PUBKEY_LEN);
            [0u8; PUBKEY_LEN]
        }
        Err(_) => {
            // Quiet fallback — typical for dev builds. The kernel logs
            // "[SEC] WARNING: dev key embedded" at runtime.
            [0u8; PUBKEY_LEN]
        }
    };

    let mut out = fs::File::create(&dest).expect("write secure_boot_pubkey.rs");
    write!(out, "// Auto-generated by build.rs — do not edit.\n").unwrap();
    write!(out, "pub(crate) const SECURE_BOOT_PUBKEY_BYTES: [u8; {}] = [",
        PUBKEY_LEN).unwrap();
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 { write!(out, ", ").unwrap(); }
        write!(out, "0x{:02x}", b).unwrap();
    }
    writeln!(out, "];").unwrap();
}
